### ISSUE TITLE
undefined reference to `probfun_'

### ISSUE THREAD

**Issue by Igor-SV** [ralna/GALAHAD#1]
Dear GALAHAD users,

I have compiled GALAHAD, but unfortunately can't even compile a simple test code.
May I ask you to compile and run the code attached?
I always have the following compilation error with this code:

gfortran -c -I/home/ishevche/GALAHAD-3.0.3/modules/pc64.lnx.gf5/double fun.f90
gfortran test_LANCELOT.f90  -o test_LANCELOT -L/home/ishevche/GALAHAD-3.0.3/objects/pc64.lnx.gf5/double -lgalahad -lgalahad_blas -lgalahad_hsl -lgalahad_metis -lgalahad_lapack -lg2c -I/home/ishevche/GALAHAD-3.0.3/modules/pc64.lnx.gf5/double fun.o
/home/ishevche/GALAHAD-3.0.3/objects/pc64.lnx.gf5/double/libgalahad.a(lancelot_simple.o): In function `__lancelot_simple_double_MOD_lancelot_simple':
lancelot_simple.f90:(.text+0x4ae5): undefined reference to `probfun_'
lancelot_simple.f90:(.text+0x4b9b): undefined reference to `probfun_'
collect2: error: ld returned 1 exit status
Makefile:21: recipe for target 'test_LANCELOT' failed
make: *** [test_LANCELOT] Error 1

Any help and suggestions will be highly appreciated!
[lancelot.zip](https://github.com/ralna/GALAHAD/files/2315106/lancelot.zip)

Best regards,
Igor

**Comment by nimgould** [comment]
Dear Igor

This appears to be a mistake by the author of the code concerning the use of the optional
function my_fun. As it stands, although an optional evaluation may be provided, the
linker also needs a routine with the name probfun. I suggest that you simply append
the dummy code 

       SUBROUTINE PROBFUN ( X, F, i )
       INTEGER, PARAMETER :: wp = KIND( 1.0D+0 ) ! set precision
       REAL( KIND = wp ), INTENT( IN )   :: X( : )
       REAL( KIND = wp ), INTENT( OUT )  :: F
       INTEGER, INTENT( IN ), OPTIONAL   :: i
       END SUBROUTINE PROBFUN

at the end of your fun.f90 code, and remake. This appears to work for me.
I suspect that earlier linkers were not as fussy about whether a function
was needed if the code didn't branch to it.

In the longer term, I will consult with the code's author to see how to remove
this requirement. My instinct is to make the name of the evaluation routine
non optional, although this has additional side effects that need to be
documented. 

Thank you for bringing this to our attention. I have updated the lancelot_simple
test examples to include the dummy code above.

Best wishes

Nick

**Comment by Igor-SV** [comment]
Dear Nick,

Thank you so much!
It is working!

Best regards,
Igor

**Comment by Igor-SV** [comment]
Dear Nick,

Is there a possibility to ask GALAHAD to optimize several functions (f1(X), f2(X), ...,fm(X)), X=(x1,x2,...,xn) in one shot?

Best regards,
Igor

**Comment by dpo** [comment]
@Igor-SV Do you mean simultaneously, under the same constraints?

**Comment by Igor-SV** [comment]
Yes, I mean simultaneously, under the same constraints.

**Comment by nimgould** [comment]
Dear Igor

The answer is no, this package is not thread safe. If you want a thread safe version, you
need to call the much more complicated lancelot in which all internal data is saved in
derived-type arguments. It would, of course, be possible to have a thread-fare version
of lancelot_simple, but one could argue that this goes against the "simple" aspect of
the name.

I hope to have removed the need for the dummy probfun that your reported earlier very
soon. Watch this space!

Best wishes

Nick

**Comment by Igor-SV** [comment]
Dear Nick,

Thank you very much for the answer. I have got a quick look at the derived data types in GALAHAD, but they don't seem to be capable of optimizing several functions simultaneously. Do you have a minimum working example which could give me an idea about how to do it?

Best regards,
Igor

**Comment by nimgould** [comment]
Sorry, Igor, I presumed you simply wanted to execute a parallel do loop
without the data from one optimization affecting the others. For lancelot
(and skipping most of the arguments), you would have something like

parallel DO i = 1, m
  CALL LANCELOT_solve( prob(i), range(i), ... , control(i), inform(i), data(i) )
end parallel DO
 
where each of the arguments is defined as an array, e.g.,
TYPE( LANCELOT_problem_type ) :: prob( m )

This is not possible with lancelot_simple, as the internal data is global
as it is not passed in a separate structure. The compiler may or may
not keep separate copies (and thus this procedure is not thread safe).

Nick

**Comment by Igor-SV** [comment]
Not really... I would like to have something like

CALL LANCELOT ( ..., MY_FUN = FUN ), 

where FUN is not just a scalar valued function, but a vector valued one.

Best regards,
Igor

Igor

**Comment by nimgould** [comment]
Dear Igor

Oh, I see. Sorry, the package does not do multi-criteria optimization.

I have updated lancelot_simple and its dependencies to remove the
need for the unnecessary probfun. All of these can be obtained using
  svn up 
in your $GALAHAD directory, and then you will need to recompile via

 cd src; make -s -f $GALAHAD/makfiles/pc64.lnx.gf5

Note that the argument list to lancelot_simple has changed slightly,
so you will have to modify your calls. See 
  $GALAHAD/src/lancelot_simple/lancelot_simples.f90
or the documentation for details.

I am now closing this issue as fixed.

Nick

**Comment by Igor-SV** [comment]
Dear Nick,

Thank you very much for updating lancelot_simple.

Best regards,
Igor
