### ISSUE TITLE
Merge folders with header files?

### ISSUE THREAD

**Issue by amontoison** [ralna/GALAHAD#104]
@nimgould We have header files in `include` and `src/dum/include`. I propose to remove the `src/dum/include` folder.
We also have two header files in `src/ampl`. It will be easier to maintain if we only have one folder.

**Comment by nimgould** [comment]
I am torn on the first. The reason to keep these separate is to avoid clashes with the real external solvers if they are provided; the dummy .h files are often shorter versions of the real ones.

For the ampl stuff, I defer to @dpo

**Comment by amontoison** [comment]
Thanks @nimgould, so it means that we should not always provide the headers in the `include` folder?

I updated Meson with #105 to always install these headers: https://github.com/ralna/GALAHAD/pull/105/files#diff-a80305467d1604478549ac2040af7adb27d5bf2d182fee70a46201dace857b01

Should I modify it?

**Comment by nimgould** [comment]
Yes, it should probably revert to what it was. But actually, even that isn't perfect, as we may replace any of the dummy external libraries with its proper one, so actually the .h files should be pointed to on an individual basis. The makefile install allows this, but how much meson can manage, I don't know

**Comment by amontoison** [comment]
With Meson, I can install the header files that I want in `include` or `src/dum/include`. What we can do is:
- if we didn't find the external libraries, we also install the header files of the dummy version;
- if we find the external libraries, we don't install additional headers because they are already provided by the external dependencies.

**Comment by nimgould** [comment]
That is a good solution, if it is possible.
