### ISSUE TITLE
Update the build system to support JuliaHSL and METIS 5

### ISSUE THREAD

**Issue by amontoison** [ralna/GALAHAD#123]
We should update the `makemaster` build system to JuliaHSL like the Meson build system.

Because JuliaHSL is compiled (and cross-compiled) by default with METIS 5 now, we should also support it in GALAHAD.
METIS4 is also not working with the new Apple M1 so it is a necessity for some users.

**Comment by nimgould** [comment]
The only use of Metis within GALAHAD is 1) if real HSL packages are called and 2) a test in the ubersolver sls to see whether metis has been provided.

Someone will need to provide the necessary interface that can detect what is available. I gather that you have such a thing for HSL.

I am happy to be guided on how to provide the alternative meson build. But I will need a lot of help!!

**Comment by amontoison** [comment]
Don't you also use METIS in Spral? I found a `metis4_wrapper.F90` and `metis5_wrapper.F90` in the folder `src/spral`.
For JuliaHSL, I added an option for the user to specify if a `libmetis.so` is found, what version of METIS it is (4 or 5).
I suppose that the user has METIS 5 by default (METIS 5 has already 10 years...).

I think that we can do similar here. An option to provide the shared library of METIS and another one to specify the version.
It seems that we only have one call to metis_nodend:
```
sls/sls.F90:1000:     CALL metis_nodend( n_dummy, PTR, ROW, 1, ICNTL_metis, INVP, PERM )
```

**Comment by nimgould** [comment]
Yes, metis is used by spral, but as far as I understood, it automatically chooses between
metis4 and 5 (the code is too complicated for me to know, I think @jari looked into it).

The sls call is to see whether metis is provided at all; we don't presume that it is, and if not the dummy metis is used

**Comment by amontoison** [comment]
Spral automatically chooses between metis 4 and 5 thanks to a complex modification of the Autotools build system.
For our `makemaster` / `meson` build systems, we can just add an option for the user to specify if we want to use METIS 4.
Otherwise we will consider that it's a METIS 5 library.

I will prepare a pull request and we will then adjust if necessary.

**Comment by amontoison** [comment]
Nick, I think that we can close the issue.
I just don't know how to test `GALAHAD` with `HSL` solvers if I compile it with `-lhsl` but it's not another issue.

**Comment by nimgould** [comment]
Yes, the makemaster version now also works with this
