### ISSUE TITLE
Windows PR runs failing

### ISSUE THREAD

**Issue by nimgould** [ralna/GALAHAD#134]
I see this for each windows PR run -

Run actions/checkout@v3
12
Syncing repository: ralna/GALAHAD
13
Getting Git version info
17
Temporarily overriding HOME='D:\a\_temp\8afcbfe7-df9e-46fa-b5d1-4925d790133f' before making global git config changes
18
Adding repository directory to the temporary git global config as a safe directory
19
"C:\Program Files\Git\bin\git.exe" config --global --add safe.directory D:\a\GALAHAD\GALAHAD
20
Deleting the contents of 'D:\a\GALAHAD\GALAHAD'
21
Initializing the repository
25
Disabling automatic garbage collection
27
Setting up auth
33
Fetching the repository
451
Determining the checkout info
452
Checking out the ref
453
  "C:\Program Files\Git\bin\git.exe" checkout --progress --force refs/remotes/pull/85/merge
454
  Error: error: invalid path 'doc/Python/aux.rst'
455
  Error: The process 'C:\Program Files\Git\bin\git.exe' failed with exit code 128

aux.rst is available on multi-precions branch, so I have no idea what is happening

**Comment by amontoison** [comment]
Fixed by the commit https://github.com/ralna/GALAHAD/pull/85/commits/69f67419f34050c336d3fc36cbff1b393b384ffa
The files `aux.*` can be only used by the system.
