### ISSUE TITLE
Meson not finding CUTEst Fortran modules

### ISSUE THREAD

**Issue by jfowkes** [ralna/GALAHAD#186]
When I try to compile with:
```
meson setup builddir -Dlibcutest_path=~/Code/CUTEst/objects/pc64.lnx.gfo/double/
...
Library cutest found: YES
...
```
then Meson can't find the required CUTEst module files:
```
../src/cutest_functions/cutest_functions.F90:22:10:

   22 |      USE CUTEST_INTERFACE_precision
      |          1
Fatal Error: Cannot open module file ‘cutest_interface_double.mod’ for reading at (1): No such file or directory
```
I guess we need to add another option?

EDIT: the module files are of course in `~/Code/CUTEst/modules/pc64.lnx.gfo/double/`.

**Comment by nimgould** [comment]
Yes, I would have thought something like -Dlibcutest_mods=

**Comment by amontoison** [comment]
@jfowkes @nimgould 
I never tested the compilation of GALAHAD with CUTEST but we probably need one option for libcutest in single precision and another one for the double precision?
It's what I did with MUMPS.
The other issue is that we need different name and soname for the single and double precision libraries (libcutest_single.a and libcutest_double.a?).

**Comment by nimgould** [comment]
I presume we can simply use symbolic links for this, i.e,
 ln -fs ./double/libcutest.a ./libcuest_double.a
 ln -fs ./single/libcutest.a ./libcuest_single.a
in each of the supported objects/architucture directories

**Comment by amontoison** [comment]
I suppose that we also need to provide two paths for the Fortran modules, one for each precision.

**Comment by amontoison** [comment]
I confirm, we have two modules with the same names `cutest.mod` and `cutest_problem.mod` in single and double precision.

**Comment by nimgould** [comment]
Yes, and suitable symlinks will sort these out
