### ISSUE TITLE
Update galahad.h?

### ISSUE THREAD

**Issue by amontoison** [ralna/GALAHAD#196]
I am wondering if we should not add a list of `#include` for all packages in the main `galahad.h`.
It's what is done in Intel MKL for example. The user can just add an `#include "mkl.h"` in its code .

**Comment by nimgould** [comment]
By this, do you simply mean adding #include "galahad_arc.h" etc? If so, yes, that is a good idea. But beware that each galahada_*.h itself includes all of the dependencies. I presume #include sorts this out

**Comment by amontoison** [comment]
Yes, I mean that. 🙂

**Comment by nimgould** [comment]
OK, can you do this, and check it works?
