### ISSUE TITLE
Upgrade SPRAL

### ISSUE THREAD

**Issue by amontoison** [ralna/GALAHAD#198]
The version of SPRAL  in GALAHAD contains many bugs that were fixed in the GitHub repository of SPRAL.
We should find an efficient way to update SPRAL here.
If we add support for single precision in the original version, we could probably include the official releases in GALAHAD and don't maintain two versions.

cc @jfowkes

**Comment by nimgould** [comment]
I thought I had fixed these in early October, but maybe there have been more over the past few weeks. I will investigate. GALAHAD doesn't want the whole of spral, just the ssids and br_read parts. In addition, ssids isn't supported under nagfor (no omp suuport).

**Comment by amontoison** [comment]
The difference is quite small Nick, SPRAL contains SSIDS, LSMR and SSMFE.
I can add an option to not compile LSMR and SSMFE.

**Comment by nimgould** [comment]
Ultimately, yes, it would be good to separate the ssids parts from galahad. but that will need someone to produce a single-precision version there ... and from what I did, the GPU part may be far from trivial - at present GALAHAD doesn't use the GPU components
