### ISSUE TITLE
Shared libraries have the same name for single and double precision

### ISSUE THREAD

**Issue by amontoison** [ralna/GALAHAD#20]
If we want that the shared libraries coexist for both precisions, we need to give them a different name when they are generated with `bin/create_shared`.

**Comment by dpo** [comment]
As far as the julia interface is concerned, it will be just as easy if everything goes into `libgalahad.so` or if we have `libgalahad_double.so` and `libgalahad_single.so`. I would say it's mostly a matter of preference, but users may find it simpler if there is only one library.

**Comment by nimgould** [comment]
That is certainly a reasonably possibility. 

Any ideas for how we deal with the names of the C interfaces?

**Comment by amontoison** [comment]
You could add `_s` or `_d` at the end the names.

**Comment by nimgould** [comment]
Since the double precision versions are already in circulation with python, I propose that we just have a _s (or maybe _single) for the single precision. We will not offer anything other than double for python

**Comment by amontoison** [comment]
Is not possible to use `_s` for single, `_d` for double and add macros just like HSL packages?
```c
#ifndef ma57_default_control
#define ma57_default_control      ma57_default_control_d
#define ma57_init_factors         ma57_init_factors_d
#define ma57_control              ma57_control_d
#define ma57_ainfo                ma57_ainfo_d
#define ma57_finfo                ma57_finfo_d
#define ma57_sinfo                ma57_sinfo_d
#define ma57_analyse              ma57_analyse_d
#define ma57_factorize            ma57_factorize_d
#define ma57_solve                ma57_solve_d
#define ma57_finalize             ma57_finalize_d
#define ma57_enquire_perm    	  ma57_enquire_perm_d
#define ma57_enquire_pivots  	  ma57_enquire_pivots_d
#define ma57_enquire_d       	  ma57_enquire_d_d
#define ma57_enquire_perturbation ma57_enquire_perturbation_d
#define ma57_enquire_scaling      ma57_enquire_scaling_d
#define ma57_alter_d              ma57_alter_d_d
#define ma57_part_solve           ma57_part_solve_d
#define ma57_sparse_lsolve        ma57_sparse_lsolve_d
#define ma57_fredholm_alternative ma57_fredholm_alternative_d
#define ma57_lmultiply            ma57_lmultiply_d
#define ma57_get_factors          ma57_get_factors_d
#endif
```

**Comment by nimgould** [comment]
I'll discuss with @jfowkes next week (remotely as its a non-working week for part-time me)

**Comment by jfowkes** [comment]
@amontoison this is indeed possible, from the HSL C interface guidelines:

> **define symbol remapping**
> C does not allow generic calls in the same way as Fortran. Each routine must therefore have a unique name. HSL data types and functions therefore have an underscore followed by a single letter appended to their name indicating their type (e.g. _d for double precision).
> 
> The typical user will only require a single specific precision variant within their code. In this case, and to simplify documentation, it is useful to omit the precision specifying suffix. This is achieved by creating an alias through the use of the C pre-processor’s #define directive, and only affects the C header file and user’s program. By placing these directives in an #ifndef block we ensure only the first header file encountered defines these aliases.

**Comment by nimgould** [comment]
The _s prefix for single has been implemented
