### ISSUE TITLE
scu_initialize is not implemented in the C interface of SCU

### ISSUE THREAD

**Issue by amontoison** [ralna/GALAHAD#231]
@nimgould 
We can't use the other C routines (`scu_information` and `scu_terminate`) if `scu_initialize` is not implemented.

**Comment by nimgould** [comment]
scu doesn't have an initialize routine as the 
fortran package doesn't have a control type.
Thus there is nothing to initialize.

At present I have not added full C interfaces to 
many of the subsidiary routines, but just the
control/inform structures (that are used by cascade
in other packages).

**Comment by amontoison** [comment]
How do you initialize the `data` parameter of `scu_information` and `scu_terminate`?

**Comment by nimgould** [comment]
You are right, the component imform%scu_data needs to be initialized on the fortran side, so I have now set default values in the definition of the tyep. Of course, there is no need for the scu c-side routines at the moment, these are simply placeholders in case someone ever writes the compete c interface (same for all of these subsidary routines), only the control/inform values are needed (if available).

Will push when I next get a chance

**Comment by amontoison** [comment]
@nimgould Can I close this issue?

**Comment by nimgould** [comment]
Yes, thanks

**Comment by amontoison** [comment]
I don't see the routine `scu_initialize` in the header file:
https://github.com/ralna/GALAHAD/blob/master/include/galahad_scu.h

**Comment by nimgould** [comment]
As I said, it is not needed, scu has no control type parameters to set.

**Comment by amontoison** [comment]
> You are right, the component imform%scu_data needs to be initialized on the fortran side, so I have now set default values in the definition of the tyep. Of course, there is no need for the scu c-side routines at the moment, these are simply placeholders in case someone ever writes the compete c interface (same for all of these subsidary routines), only the control/inform values are needed (if available).
> 
> Will push when I next get a chance

👆👆👆
You still need to initialize the `data` parameter that is created in Julia or C.

**Comment by nimgould** [comment]
Presumably, this can be done on the C side?

**Comment by amontoison** [comment]
I can't do it directly in Julia.
This is my test for `SCU` in Julia:
```julia
# test_scu.jl
# Simple code to test the Julia interface to SCU

using GALAHAD
using Test

function test_scu()
  data = Ref{Ptr{Cvoid}}()
  control = Ref{scu_control_type}()
  inform = Ref{scu_inform_type}()

  status = Ref{Cint}()
  scu_initialize(data, control, status)
  scu_information(data, inform, status)
  scu_terminate(data, control, inform)

  return 0
end

@testset "SCU" begin
  @test test_scu() == 0
end
```
Because the C function `scu_initialize` is missing, I can run the test.
