### ISSUE TITLE
C interface of lhs

### ISSUE THREAD

**Issue by amontoison** [ralna/GALAHAD#24]
We should replace `int X[n_dimen][n_points]` by `int **X` [here](https://github.com/ralna/GALAHAD/blob/master/include/galahad_lhs.h#L182).
I was not able to generate the Julia interface of `lhs` and `bgo` because of it.
https://github.com/JuliaInterop/Clang.jl/discussions/395#discussioncomment-4153444

**Comment by nimgould** [comment]
@jfowkes can you comment here, is that a good way to access a 2-D array? Sorry, my C isn't strong enough to be sure.

**Comment by jfowkes** [comment]
@amontoison you need to enable a modern C standard (at least C99 or better C11)

**Comment by amontoison** [comment]
Do you have a difference if you use `int X[n_dimen][n_points]` or `int **X` in C?
It's `Ptr{Ptr{Cint}} in both cases in Julia.

@jfowkes It's not related to a C standard here, it's the Julia package `Clang.jl` that doesn't support this type of argument.

**Comment by jfowkes** [comment]
We prefer `int X[n_dimen][n_points]` as it is much clearer to the user in terms of what dimension does what and thus less likely to lead to bugs unlike a generic `int **X`.

@amontoison this is the variable length-array (VLA) as implemented in C99 therefore `Clang.jl` should support it, otherwise it needs to be updated so that is standards compliant:
https://en.wikipedia.org/wiki/Variable-length_array

**Comment by nimgould** [comment]
And while C might not check the dimensions, the iso-C bindings to fortran rely on C being implemented according to C99

**Comment by nimgould** [comment]
I tried changing the int X[n_dimen][n_points] to int **X in the .h file, but the compiler now grumbles when using the test example

Compiling lhsct          		lhsct.c: In function ‘main’:
lhsct.c:28:39: warning: passing argument 4 of ‘lhs_ihs’ from incompatible pointer type [-Wincompatible-pointer-types]
   28 |     lhs_ihs(n_dimen, n_points, &seed, X, &control, &inform, &data);
      |                                       ^
      |                                       |
      |                                       int (*)[n_points]
In file included from lhsct.c:6:
/home/nimg/fortran/optrove_standalone/galahad/include/galahad_lhs.h:182:21: note: expected ‘int **’ but argument is of type ‘int (*)[n_points]’
  182 |               int **X,
      |               ~~~~~~^
 
The test example still works, I should add

Do I need to change something else? Certainly the test program expects to pass in data  X[i][j]

Unless we can remove this warning message, I would be reluctant to make this change. Really this is a clang issue not a c one is this is a standard c11 program

**Comment by nimgould** [comment]
In the response you got from the clang.jl person, "Just Clang.jl, I didn't implement it. You can treat int X[n_dimen][n_points] as int** and manually write a wrapper." do you know what this means? Can we do that? I'm not a C person, but maybe you know?

**Comment by dpo** [comment]
@nimgould I did not look at the source code, but just a thought: you might have to cast X as `int**` when you call the function:
```c
lhs_ihs(n_dimen, n_points, &seed, (int**)X, &control, &inform, &data);
```

**Comment by amontoison** [comment]
> In the response you got from the clang.jl person, "Just Clang.jl, I didn't implement it. You can treat int X[n_dimen][n_points] as int** and manually write a wrapper." do you know what this means? Can we do that? I'm not a C person, but maybe you know?

A wrapper is a Julia function that calls a C or a Fortran routine.
"manually write a wrapper" means that I can write myself the following Julia function: https://github.com/amontoison/GALAHAD.jl/blob/main/src/C/lhs.jl#L28-L33
It's what I need to do for packages without C interfaces such as many HSL packages for instance :smiling_face_with_tear:.
An example is MC21 (https://github.com/JuliaSmoothOptimizers/HSL.jl/blob/main/src/mc21.jl#L12-L17). 

To avoid it, I directly replaced `int X[n_dimen][n_points]` by `int **X` in `galahad_lhs.h` such that `Clang.jl` can generate a wrapper.
By chance it's the ONLY C routine that Clang.jl can't handled and you can keep `int X[n_dimen][n_points]` if it's clearer.
I can do this small modification by hand if I want to regenerate the Julia wrapper.
From a Julia point of view, `X` will be stored as a "Julia vector of Julia vectors" and we will always provide it as a `Ptr{Ptr{Cint}}` to C routines.

The Clang.jl person didn't expected that a variable length-array (VLA) was used in a C function and he just didn't implemented a generator for Julia wrappers with this kind of arguments.
If it's supported one day, the result will be same for the Julia wrapper, `X` will be represented as `Ptr{Ptr{Cint}}`.

He didn't implemented it because Julia mirror of C structures with VAL attributes are not supported in Julia structures BUT it's still supported by Julia functions.
You will understand why with the following example:
when we use an attribute of a Julia structure as an argument of a C routine, Julia will just give a pointer to the C routine and it's a correct pointer because he knows exactly the length of the other attributes (all attributes are typed) and he just needs to add a offset of `n_i` bits where `n_i` is the total number of bits of all previous attributes in the structure.
You can easily understand why the 32 bits `Clong` is an issue if I represent it as a `Int64` in Julia.
All attributes after `max_factor_size` in this [structure](https://github.com/amontoison/GALAHAD.jl/blob/main/src/C/uls.jl#L11) will have a wrong pointer / value :fearful:

**Comment by nimgould** [comment]
Hurrah, the cast (int**)X worked; as always this simply exposes my ignorance of C! I've updated the header file and test example, accordingly, and will push this afternoon after I have made a few other changes elsewhere.
