### ISSUE TITLE
[CI] Install C Regex Library on Windows

### ISSUE THREAD

**Issue by jfowkes** [ralna/GALAHAD#277]
All versions of METIS require a C Regex library (`-lregex`) but this is not present on Windows.

@amontoison can we install one of the following MinGW C Regex libraries on Windows?
https://stackoverflow.com/questions/3781211/c-regex-library-with-mingw

**Comment by nimgould** [comment]
The lack of the regex library is now the failure reason for both gcc and icx, so we definitely need it. Metis 5.1 compilation would fail for the same reason

**Comment by amontoison** [comment]
When we cross-compiled METIS 5.1 with MinGW for the Julia ecosystem, we added these two patches:
- https://github.com/JuliaPackaging/Yggdrasil/blob/master/M/METIS/METIS%405/bundled/patches/0001-mingw-w64-does-not-have-sys-resource-h.patch
- https://github.com/JuliaPackaging/Yggdrasil/blob/master/M/METIS/METIS%405/bundled/patches/0002-mingw-w64-do-not-use-reserved-double-underscored-names.patch

Does it help for this issue?

**Comment by nimgould** [comment]
Thanks, but I suspect not as these header files have already been improved and extended in Metis 5.2. The isseue is that meson is not loading the required regex library that is only optional for Mingw

**Comment by amontoison** [comment]
Fixed in #272
