### ISSUE TITLE
[CI] Check modules failing

### ISSUE THREAD

**Issue by jfowkes** [ralna/GALAHAD#278]
@amontoison check modules is failing for some reason?

**Comment by amontoison** [comment]
I try to do a meeting with you @nimgould and @jfowkes about that since February.
Let's do a meeting please.

**Comment by nimgould** [comment]
Yes, when are you free. We are around both this week and next

**Comment by amontoison** [comment]
Next week I'm free. Is Tuesday fine for you?
I'm also free other days if needed.

**Comment by nimgould** [comment]
Yes, next Tuesday. Will you back in Canada/USA? How about 3PM our time?

**Comment by amontoison** [comment]
As we discussed yesterday, it's failing because the Fortran modules are the same in single and double precision and could collapse.
- With 32-bit integer: `pastixf_interfaces.mod` and `spmf_interfaces.mod`.
- With 64-bit integer: `pastixf_interfaces_64.mod` and `spmf_interfaces_64.mod`.

**Comment by nimgould** [comment]
I have changed these modules so that they now have a _double_64 (etc) suffix. But as they are only interfaces, it is not obvious to me how a prebuilt pastix will be able to use these, as the internal interface blocks are to the pastix library-defined (e.g.)  pastix_task_analyze_f08 which
has the same name in single/double and 32/64-bit integer. This is unlike, for example, HSL where the HSL packages have unique real and integer-dependent names.

**Comment by nimgould** [comment]
Now getting

1s
1
Run julia --color=yes .github/julia/check_modules.jl
17
ERROR: LoadError: IOError: readdir("/home/runner/work/GALAHAD/GALAHAD/.github/julia/../../builddir_int64/libgalahad_single.so.p"): no such file or directory (ENOENT)
18
Stacktrace:
19
 [1] uv_error
20
   @ ./libuv.jl:100 [inlined]
21
 [2] readdir(dir::String; join::Bool, sort::Bool)
22
   @ Base.Filesystem ./file.jl:869
23
 [3] readdir
24
   @ ./file.jl:862 [inlined]
25
 [4] exported_modules(path::String)
26
   @ Main ~/work/GALAHAD/GALAHAD/.github/julia/check_modules.jl:7
27
 [5] top-level scope
28
   @ ~/work/GALAHAD/GALAHAD/.github/julia/check_modules.jl:18
29
in expression starting at /home/runner/work/GALAHAD/GALAHAD/.github/julia/check_modules.jl:18

Any idea what this all means?

**Comment by jfowkes** [comment]
@amontoison it looks like the Julia modules script is now broken?

**Comment by amontoison** [comment]
I just fixed it.
It's because I added the suffix `_64` for the shared libraries compiled with 64-bits integer (see https://github.com/ralna/GALAHAD/pull/272/commits/3fdefd723bd330c5efefc6a1021e9d500104b03e).

Off-topic: You wrote a great README, Jari!

**Comment by amontoison** [comment]
FIxed on the branch `galahad5-nick`.
