### ISSUE TITLE
Issue "Testing ... interface to cdqp"

### ISSUE THREAD

**Issue by frankecurtis** [ralna/GALAHAD#28]
I have encountered errors when running the general tests of GALAHAD using the instructed command:

`make -f $GALAHAD/makefiles/# tests`

In both cases, the error is encountered when "Testing [some] interface to cdqp".

1) The first time I encountered an issue, I had installed GALAHAD (using install_optrove) without selecting the CUTEst interface.  Therefore, I was surprised when I encountered an error during "Testing CUTEst interface to cdqp".  (Why was it being run at all?)  Not surprisingly, the error I got said: `ld: library not found for -lcutest`

2) The second time I encountered an issue, I had re-installed GALAHAD with the CUTEst interface.  This time, the tests made it through the CUTEst interface to cdqp, but an error was subsequently encountered during "Testing QPLIB interface to cdqp".  I repeat it below:

```
          dgal mac.osx.gfo cdqp QPBAND.qplib
 Unfortunately no data file version of cdqp is available at presnt.
make[2]: *** [test_cdqp_qplib_double] Error 2
make[1]: *** [make_cdqp_tests] Error 2
make: *** [tests_double] Error 2
```

**Comment by nimgould** [comment]
This was an oversight in the dgal script in which the cdqp solver was accidentally left of the list of those we support. Thanks! Now added and tested. Re-up very shortly
