### ISSUE TITLE
Clong has been replaced by int64_t in the HSL headers

### ISSUE THREAD

**Issue by amontoison** [ralna/GALAHAD#283]
@nimgould @jfowkes

I regenerated the Julia wrappers for `GALAHAD.jl` and I observed that you replaced `Clong` with `int64_t` in the HSL headers.

This change means it's a breaking change for Windows users. They won't be able to use any previous HSL package or libHSL.

`hsl_subset` will be mandatory in all cases for Windows users, even if they use the HSL routines with 32-bit integers.
Do you want to proceed with this modification?

I propose to add a macro so we can maintain backward compatibility with HSL packages on Windows.
Something like `-DHSL_LEGACY` should be sufficient.
We can use it to define `hsl_ipc_` as `Clong` with this macro and `int64_t` otherwise.

**Comment by nimgould** [comment]
I think that this is a change that we want going forward with sparse HSL and GALAHAD so that we can be precise about our requirements for integers. I believe that this was discussed in depth by the HSL folk. Jari can tell us ... but not this week as he is away on leave.

**Comment by jfowkes** [comment]
Yes as Nick says this has not changed for libHSL precisely so it does not break Windows but will be the SparseHSL default.

**Comment by amontoison** [comment]
You just explained that it breaks Windows Jari.

If you expect some attributes in HSL structures to be `int64_t`, you can't compile the HSL solvers with these attributes as `Clong` on Windows.

**Comment by jfowkes** [comment]
Yes the plan is to switch from Clong to int64_t in the C interfaces for SparseHSL, but in the meantime what we currently have here will of course break on Windows. I suggest that we use a macro for now as you suggest.

**Comment by amontoison** [comment]
@jfowkes @nimgould 
Why did you keep `clong` in MC68?
Did you forget it?
I checked the include files of `hsl_subset`.

```
struct mc68_info {
   ipc_ flag;            /* error/warning flag */
   ipc_ iostat;          /* holds Fortran iostat parameter */
   ipc_ stat;            /* holds Fortran stat parameter */
   ipc_ out_range;       /* holds number of out of range entries ignored */
   ipc_ duplicate;       /* holds number of duplicate entries */
   ipc_ n_compressions;  /* holds number of compressions in order */
   ipc_ n_zero_eigs;     /* holds the number of zero eigs from ma47 */
   long l_workspace;     /* holds length of workspace iw used in order */
   ipc_ zb01_info;       /* holds flag from zb01_expand1 call */
   ipc_ n_dense_rows;    /* holds number of dense rows from amdd */
};
```

**Comment by amontoison** [comment]
> Yes the plan is to switch from Clong to int64_t in the C interfaces for SparseHSL, but in the meantime what we currently have here will of course break on Windows. I suggest that we use a macro for now as you suggest.

@jfowkes I started to add a macro `HSL_LEGACY` but it requires too many modifications...
It will be also harder to test if we have too many combinaisons.

We can keep `int64_t` here but we need to include `hsl_subset` in `libhsl` and `HSL_jll.jl` if we want to keep support for HSL solvers in GALAHAD.jl for Windows users.

**Comment by jfowkes** [comment]
@amontoison yes I see best discuss with @nimgould on how best to proceed here.

**Comment by nimgould** [comment]
This is a mistake, long here should be int_64_t to allign the fortran and C . I have corrected this locally (in hsl_mc68.h) , but I have lost track of where hsl_subset is on the HSL repo (if at all). Do you know, @jfowkes ?

**Comment by jfowkes** [comment]
No idea, you'll have to ask @AndrewLister-STFC if hsl_subset made it in to the HSL repo.

**Comment by nimgould** [comment]
OK, as far as I recall I put it onto the sparseHSL website, but that isn't openly available is it? Once GALAHAD 5 goes live, I will update the HSL for GALAHAD with these subset codes. It is a subset in that it is functionally equivalent to the official HSL for 32 bit integers (but with bug and warning fixes) for the subset of packages that are used in optimization,,but extends HSL (proprely) for 64 bit integers (no compiler promotion of 32->64 bit as this breaks logicals as well). The intention is only ever to update this as fixes are put in to proper HSL, and I monitor this by hand. 

@amontoison , you should make the change I mention above for your version.

**Comment by amontoison** [comment]
Don't forget that I don't work at RAL, Nick. I don't have the same access as you.
Right now, the HSL subset is not tested with CI and is not available on any versioned repository.
We also have a few bugs, and it doesn't compile on Windows.
From my point of view, it's not ready yet for GALAHAD5.

Nick, I will not update my version.
We have tools like Git in 2024, and they have been developed for that.
I created the following MR: https://gitlab.stfc.ac.uk/cmg/hsl/-/merge_requests/489
Please make the modifications directly on the Gitlab repository or in a place where I can track them.

@AndrewLister-STFC, what is the best solution to test `libHSL` and `hsl_subset` here on the public GitHub repository `ralna/GALAHAD`?

I was thinking of storing the archives on Dropbox/Google Drive and downloading them for CI with a secret environment variable.
What do you think?
Is it fine, or do we need to find an alternative?

**Comment by nimgould** [comment]
I do understand, Alexis. I agree that the subset should not be part of GALAHAD 5, nor was it ever intended to be as it is commercial software. But I have tested it under Linux with the make system, and we allow users to download and compile this optionally if they want.

If there are bugs, please let me know what they are and I will fix them. The only one you mentioned, I thought we had fixed? I'm sorry, I missed your MR, I'll have a look right now

**Comment by AndrewLister-STFC** [comment]
> @AndrewLister-STFC, what is the best solution to test `libHSL` and `hsl_subset` here on the public GitHub repository `ralna/GALAHAD`?
> 
> I was thinking of storing the archives on Dropbox/Google Drive and downloading them for CI with a secret environment variable. What do you think? Is it fine, or do we need to find an alternative?

That sounds possible though a bit hacky and annoying to maintain (I could see the 3rd site getting out of sync quite easily). What tests are you planning, and what's likely to break the tests? If it's just some small end to end tests and the main worry is a change in HSL, would it be sufficient to do it on the HSL CI instead? We could also rig a nightly to fetch this repo and run tests if it has been edited? Still not quite as nice as having tests on the PR's.

**Comment by nimgould** [comment]
I responded to the pull request, and the HSL repo now shows an hsl_subset directorty. But when I git up, it doesn't arrive. Is it on another branch?

**Comment by jfowkes** [comment]
It appears to be on the master branch as expected:
https://gitlab.stfc.ac.uk/cmg/hsl/-/tree/master/hsl_subset

**Comment by jfowkes** [comment]
Quite possibly, probably best to re-clone the repo.

**Comment by nimgould** [comment]
Ooops, I was on the wrong branch!

OK, if I want to make a change to a file in hsl_subset, presumably I need to open a pull request. I haven't done this before, what are the gotchas?

**Comment by nimgould** [comment]
(indeed, do I have to use the web interface, or can I do this as usual from the command line?)

**Comment by jfowkes** [comment]
You can do this from the command line by:

1. Creating a new branch based off of master (git checkout -b new-branch-name)
2. Commiting your changes to that branch
3. Pushing the new branch
4. Clicking create merge request on gitlab

**Comment by amontoison** [comment]
We added an option `hsl_legacy` here and in `hsl_subset`.
I can close this issue.
