### ISSUE TITLE
Python solve routines should allow keyword arguments

### ISSUE THREAD

**Issue by jfowkes** [ralna/GALAHAD#296]
Currently all the Python solve routines accept positional-only arguments (as Python calls it), i.e.
```Python
arc.solve(2, np.array([1.,1.]))
```
As requested by @AndrewLister-STFC, it is more Pythonic to also support keyword arguments when the arguments themselves are non-trivial or when there are a lot of them and it is difficult to keep track, i.e.
```Python
arc.solve(n=2, x=np.array([1.,1.]))
```
is much friendlier to the Python user.

In order to make this change we need to upgrade the parsing in all package solve routines, from:
```C
static PyObject* py_arc_solve(PyObject *self, PyObject *args){
...
// Parse positional arguments
    if(!PyArg_ParseTuple(args, "iiOOOO", &n, &H_ne, &py_x, &temp_f, &temp_g, &temp_h))
        return NULL;
...
}

/* arc python module method table */
static PyMethodDef arc_module_methods[] = {
...
    {"solve", (PyCFunction) py_arc_solve, METH_VARARGS, NULL},
...
};
```
to support positional-or-keyword arguments (as Python officially terms it):
```C
static PyObject* py_arc_solve(PyObject *self, PyObject *args, PyObject *keywds){
...
// Parse positional or keyword arguments
static char *kwlist[] = {"n", "H_ne", "x", "eval_f", "eval_g", "eval_h", NULL};
    if(!PyArg_ParseTupleAndKeywords(args, keywds, "iiOOOO", kwlist, &n, &H_ne, &py_x, &temp_f, &temp_g, &temp_h))
        return NULL;
...
}

/* arc python module method table */
static PyMethodDef arc_module_methods[] = {
...
    {"solve", (PyCFunction) py_arc_solve, METH_VARARGS | METH_KEYWORDS, NULL},
...
};
```

I am happy to implement this at some point when I have some free time (as really I should have templated it this way to begin with), but this will not be anytime soon I'm afraid.

References: [How does PyArg_ParseTupleAndKeywords work?](https://stackoverflow.com/questions/10625865/how-does-pyarg-parsetupleandkeywords-work)

**Comment by nimgould** [comment]
I agree. The big question is, should this happen for version 5 or 5.1? My concern is that if we don't do it now, we may get a bad reputation when python users give it a whirl

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Jari ***@***.***>
Sent: Friday, June 14, 2024 4:14:38 PM
To: ralna/GALAHAD ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ralna/GALAHAD] Python solve routines should allow keyword arguments (Issue #296)


Currently all the Python solve routines accept positional-only arguments (as Python calls it), i.e.

arc.solve(2, np.array([1.,1.]))

As requested by @AndrewLister-STFC<https://github.com/AndrewLister-STFC>, it is more Pythonic to have keyword arguments when the arguments themselves are non-trivial or when there are a lot of them and it is difficult to keep track, i.e.

arc.solve(n=2, x=np.array([1.,1.]))

is much friendlier to the Python user.

In order to make this change we need to upgrade the parsing in all package solve routines, from:

static PyObject* py_arc_solve(PyObject *self, PyObject *args){
...
// Parse positional arguments
    if(!PyArg_ParseTuple(args, "iiOOOO", &n, &H_ne, &py_x, &temp_f, &temp_g, &temp_h))
        return NULL;
...
}

/* arc python module method table */
static PyMethodDef arc_module_methods[] = {
...
    {"solve", (PyCFunction) py_arc_solve, METH_VARARGS, NULL},
...
};

to support positional-or-keyword arguments (as Python officially terms it):

static PyObject* py_arc_solve(PyObject *self, PyObject *args, PyObject *keywds){
...
// Parse positional keyword arguments
static char *kwlist[] = {"n", "H_ne", "x", "eval_f", "eval_g", "eval_h", NULL};
    if(!PyArg_ParseTupleAndKeywords(args, keywds, "iiOOOO", kwlist, &n, &H_ne, &py_x, &temp_f, &temp_g, &temp_h))
        return NULL;
...
}

/* arc python module method table */
static PyMethodDef arc_module_methods[] = {
...
    {"solve", (PyCFunction) py_arc_solve, METH_VARARGS | METH_KEYWORDS, NULL},
...
};

I am happy to implement this at some point when I have some free time (as really I should have templated it this way to begin with), but this will not be anytime soon I'm afraid.

References: How does PyArg_ParseTupleAndKeywords work?<https://stackoverflow.com/questions/10625865/how-does-pyarg-parsetupleandkeywords-work>

**Comment by jfowkes** [comment]
Yes agreed, probably best to do it now then. Will try and find some time next week.

**Comment by nimgould** [comment]
Is there any easy way to automate the changes, that is to write a program that takes the current input method and constructs the keyword alternative? Of course we will also need to extend the tests to cope with this alternative, and I am not sure what that means for the documentation

Sent from Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by jfowkes** [comment]
Yes it should be a relatively easy search and replace for the most part. There is no need to change the documentation or the tests as Python users expect positional-or-keyword arguments since it is the Python default:
https://docs.python.org/3/glossary.html#term-parameter

**Comment by nimgould** [comment]
That sounds good. Just so long as the tests examine whether keyword calls work, can we ensure that?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jfowkes** [comment]
We can only test that by adding keywords to all tests unfortunately, but that is doable.

**Comment by jfowkes** [comment]
Here is the complete list of interfaces that need upgrading:
```
$ grep -r 'METH_VARARGS,'
wcp/Python/wcp_pyiface.c:    {"find_wcp", (PyCFunction) py_wcp_find_wcp, METH_VARARGS, NULL},
lsqp/Python/lsqp_pyiface.c:    {"solve_qp", (PyCFunction) py_lsqp_solve_qp, METH_VARARGS, NULL},
dps/Python/dps_pyiface.c:     METH_VARARGS, NULL},
dps/Python/dps_pyiface.c:     METH_VARARGS, NULL},
arc/Python/arc_pyiface.c:    {"solve", (PyCFunction) py_arc_solve, METH_VARARGS, NULL},
lpa/Python/lpa_pyiface.c:    {"solve_lp", (PyCFunction) py_lpa_solve_lp, METH_VARARGS, NULL},
cqp/Python/cqp_pyiface.c:    {"solve_qp", (PyCFunction) py_cqp_solve_qp, METH_VARARGS, NULL},
cqp/Python/cqp_pyiface.c:    {"solve_sldqp", (PyCFunction) py_cqp_solve_sldqp, METH_VARARGS, NULL},
cro/Python/cro_pyiface.c:     METH_VARARGS, NULL},
trs/Python/trs_pyiface.c:    {"solve_problem", (PyCFunction) py_trs_solve_problem, METH_VARARGS, NULL},
llsr/Python/llsr_pyiface.c:    {"solve_problem", (PyCFunction) py_llsr_solve_problem, METH_VARARGS, NULL},
tru/Python/tru_pyiface.c:    {"solve", (PyCFunction) py_tru_solve, METH_VARARGS, NULL},
hash/Python/hash_pyiface.c:    {"initialize", (PyCFunction) py_hash_initialize, METH_VARARGS, NULL},
nls/Python/nls_pyiface.c:    {"solve", (PyCFunction) py_nls_solve, METH_VARARGS, NULL},
psls/Python/psls_pyiface.c:    {"load", (PyCFunction) py_psls_load, METH_VARARGS, NULL},
psls/Python/psls_pyiface.c:      (PyCFunction) py_psls_form_preconditioner, METH_VARARGS, NULL},
psls/Python/psls_pyiface.c:      (PyCFunction) py_psls_form_subset_preconditioner, METH_VARARGS, NULL},
psls/Python/psls_pyiface.c:      (PyCFunction) py_psls_apply_preconditioner, METH_VARARGS, NULL},
bqpb/Python/bqpb_pyiface.c:    {"solve_qp", (PyCFunction) py_bqpb_solve_qp, METH_VARARGS, NULL},
bqpb/Python/bqpb_pyiface.c:    {"solve_sldqp", (PyCFunction) py_bqpb_solve_sldqp, METH_VARARGS, NULL},
gltr/Python/gltr_pyiface.c:    {"solve_problem", (PyCFunction) py_gltr_solve_problem, METH_VARARGS, NULL},
uls/Python/uls_pyiface.c:    {"initialize", (PyCFunction) py_uls_initialize, METH_VARARGS,NULL},
uls/Python/uls_pyiface.c:      METH_VARARGS, NULL},
uls/Python/uls_pyiface.c:    {"solve_system", (PyCFunction) py_uls_solve_system, METH_VARARGS, NULL},
bgo/Python/bgo_pyiface.c:    {"solve", (PyCFunction) py_bgo_solve, METH_VARARGS, NULL},
ugo/Python/ugo_pyiface.c:    {"solve", (PyCFunction) py_ugo_solve, METH_VARARGS, NULL},
blls/Python/blls_pyiface.c:    {"solve_ls", (PyCFunction) py_blls_solve_ls, METH_VARARGS, NULL},
lstr/Python/lstr_pyiface.c:    {"solve_problem", (PyCFunction) py_lstr_solve_problem, METH_VARARGS, NULL},
qpb/Python/qpb_pyiface.c:    {"solve_qp", (PyCFunction) py_qpb_solve_qp, METH_VARARGS, NULL},
trb/Python/trb_pyiface.c:    {"solve", (PyCFunction) py_trb_solve, METH_VARARGS, NULL},
qpa/Python/qpa_pyiface.c:    {"solve_qp", (PyCFunction) py_qpa_solve_qp, METH_VARARGS, NULL},
qpa/Python/qpa_pyiface.c:    {"solve_l1qp", (PyCFunction) py_qpa_solve_l1qp, METH_VARARGS, NULL},
qpa/Python/qpa_pyiface.c:    {"solve_bcl1qp", (PyCFunction) py_qpa_solve_bcl1qp, METH_VARARGS, NULL},
glrt/Python/glrt_pyiface.c:    {"solve_problem", (PyCFunction) py_glrt_solve_problem, METH_VARARGS, NULL},
bqp/Python/bqp_pyiface.c:    {"solve_qp", (PyCFunction) py_bqp_solve_qp, METH_VARARGS, NULL},
fdc/Python/fdc_pyiface.c:      METH_VARARGS, NULL},
lsrt/Python/lsrt_pyiface.c:    {"solve_problem", (PyCFunction) py_lsrt_solve_problem, METH_VARARGS, NULL},
rqs/Python/rqs_pyiface.c:    {"solve_problem", (PyCFunction) py_rqs_solve_problem, METH_VARARGS, NULL},
dqp/Python/dqp_pyiface.c:    {"solve_qp", (PyCFunction) py_dqp_solve_qp, METH_VARARGS, NULL},
dqp/Python/dqp_pyiface.c:    {"solve_sldqp", (PyCFunction) py_dqp_solve_sldqp, METH_VARARGS, NULL},
bllsb/Python/bllsb_pyiface.c:    {"solve_bllsb", (PyCFunction) py_bllsb_solve_blls, METH_VARARGS, NULL},
sls/Python/sls_pyiface.c:    {"initialize", (PyCFunction) py_sls_initialize, METH_VARARGS,NULL},
sls/Python/sls_pyiface.c:    {"analyse_matrix", (PyCFunction) py_sls_analyse_matrix, METH_VARARGS, NULL},
sls/Python/sls_pyiface.c:      METH_VARARGS, NULL},
sls/Python/sls_pyiface.c:    {"solve_system", (PyCFunction) py_sls_solve_system, METH_VARARGS, NULL},
sls/Python/sls_pyiface.c:      METH_VARARGS, NULL},
dgo/Python/dgo_pyiface.c:    {"solve", (PyCFunction) py_dgo_solve, METH_VARARGS, NULL},
llst/Python/llst_pyiface.c:    {"solve_problem", (PyCFunction) py_llst_solve_problem, METH_VARARGS, NULL},
l2rt/Python/l2rt_pyiface.c:    {"solve_problem", (PyCFunction) py_l2rt_solve_problem, METH_VARARGS, NULL},
eqp/Python/eqp_pyiface.c:    {"solve_qp", (PyCFunction) py_eqp_solve_qp, METH_VARARGS, NULL},
eqp/Python/eqp_pyiface.c:    {"solve_sldqp", (PyCFunction) py_eqp_solve_sldqp, METH_VARARGS, NULL},
sbls/Python/sbls_pyiface.c:    {"load", (PyCFunction) py_sbls_load, METH_VARARGS, NULL},
sbls/Python/sbls_pyiface.c:      METH_VARARGS, NULL},
sbls/Python/sbls_pyiface.c:    {"solve_system", (PyCFunction) py_sbls_solve_system, METH_VARARGS, NULL},
lpb/Python/lpb_pyiface.c:    {"solve_lp", (PyCFunction) py_lpb_solve_lp, METH_VARARGS, NULL},
slls/Python/slls_pyiface.c:    {"solve_ls", (PyCFunction) py_slls_solve_ls, METH_VARARGS, NULL},
```
Thankfully not as many as I thought.

**Comment by nimgould** [comment]
Do you want to create a branch; I am happy to help, we can divide and conquer, I could start from the end, and you can march forward until we meet. Or do you have some global substitution that will swat them all at the same time? Remember, we need to test as we go. 

If you are using the makefile version, you should 
a) make -s -f $GALAHAD/makefiles/(your archname) all_pyiface
, where (your archname) is the file in that directory that gives your machine/os/compiler
combo,  to build the current python system and then after editing each package pack
b) cd pack ; make -s -f $GALAHAD/makefiles/(your archname) test_pack_pyiface

**Comment by jfowkes** [comment]
Have done the main work, see the pull request #301 

Could you have a go at adding keyword arguments to the tests? I.e. `ugo.solve(x=x)`. 

Also there are lots of typos in the function arguments in the docs, e.g. h_ne, a_ne instead of H_ne, A_ne and various extra variables or missing variables.
