### ISSUE TITLE
Add a routine to return the version number of GALAHAD

### ISSUE THREAD

**Issue by amontoison** [ralna/GALAHAD#321]
@jfowkes As we discussed during ISMP.

**Comment by jfowkes** [comment]
@nimgould as we discussed with @amontoison last week, it would be really useful to have a little GALAHAD program that simply returns the version number.

**Comment by nimgould** [comment]
Yes, it would be good to have this, but what version number do we mean? I used to have a file version in the main directory, but @amontoison removed it for some reason (I can't remember why, but I seem to recall it was a good one!). Really, it would be good to sync version numbers between the package and the github, so that each commit corresponds to a minor number change. But how do we automate that?

**Comment by amontoison** [comment]
We want a C or Fortran routine thay returns the version of the current release.
The text file that was in the GALAHAD repository was not updated since GALAHAD 3.3 and we can't recover it from any compiled code.

For example, what is the version of GALAHAD that I'm using from Python or Julia if I only have a `libgalahad_double.so` with me.

**Comment by nimgould** [comment]
I presume that we want a version number that is only updated when we issue a release. In that case, I'll put back a file "version" that contains that number, and add a package with a single function to return that number. Do you want a character (e.g. 5.0.1) , or three integers (5, 0 and 1 
 for the major minor patch values)? Of course, we must remember to update the version file when we make a new release! There is a long discussion in https://stackoverflow.com/questions/37814286/how-to-manage-the-version-number-in-git about this, and I am sure you git experts will understand better than me if this can be automated

**Comment by nimgould** [comment]
I've added a module (galahad_version) that has a single function 
string = version( )
that puts a handcoded version string (major.minor.patch) into the variable string.
Of course we will need to update this every time we update the version!

**Comment by nimgould** [comment]
(galahad.jl failing for this upgrade, some timeout)

**Comment by amontoison** [comment]
@nimgould I think that using three integers is better for interoperability.
I did something similar for libHSL:
```h
/* Version number of HSL_MA57 */
#define HSL_MA57_VER_MAJOR 5
#define HSL_MA57_VER_MINOR 3
#define HSL_MA57_VER_PATCH 2
void HSL_MA57_version(int *major, int *minor, int *patch);
```
```c
void HSL_MA57_version(int *major, int *minor, int *patch) {
    *major = HSL_MA57_VER_MAJOR;
    *minor = HSL_MA57_VER_MINOR;
    *patch = HSL_MA57_VER_PATCH;
}
```
This was in C, but we can probably define the three integers directly in Fortran.
What do you think?

**Comment by nimgould** [comment]
No problem, something for next week

**Comment by amontoison** [comment]
No rush 😉

**Comment by nimgould** [comment]
Done
