### ISSUE TITLE
HSL symbols are not correctly preprocessed

### ISSUE THREAD

**Issue by amontoison** [ralna/GALAHAD#327]
![Capture d’écran du 2024-10-09 19-47-04](https://github.com/user-attachments/assets/f778c8ad-18d9-48d1-b608-9b56d43ce96e)
The macros are correct; we have the same ones in the official `hsl_subset`.
However, the names of the subroutines are not the same, which explains why they are not correctly preprocessed.

cc @nimgould

**Comment by nimgould** [comment]
GALAHAD does not provide C interfaces to hsl packages - you are comparing the dummy fortran interface external/hsl/hsl_ma48/hsl_ma48r.f90  to the true subset C interface. All access to HSL codes in GALAHAD is
through the appropriate calling fortran package (usually SLS or ULS)
