### ISSUE TITLE
Issues with PasTiX subroutines

### ISSUE THREAD

**Issue by amontoison** [ralna/GALAHAD#40]
```shell
../src/sls/sls.F90:1306:67:

 1306 |        CALL pastixInitParam( data%iparm_pastix, data%dparm_pastix )
      |                                                                   1
Error: There is no specific subroutine for the generic ‘pastixinitparam’ at (1)
../src/sls/sls.F90:1316:62:

 1316 |                         data%iparm_pastix, data%dparm_pastix )
      |                                                              1
Error: There is no specific subroutine for the generic ‘pastixinit’ at (1)
```
It's probably related to `src/dum/pastixf.F90`,  `src/dum/pastixf_enums.F90` or `src/dum/pastixf_interfaces.F90`.

**Comment by nimgould** [comment]
I don't know what the issue is, it works fine here with all compilers. Presumably the call to pastixInitParam is trying to match that according to the interfaces in the pastixf_interfaces, and this should match. Is this single or double?

**Comment by amontoison** [comment]
I have the same issue in single and double precision.
With Intel compiler, I have the following error:
```
../src/sls/sls.F90(1306): error #6285: There is no matching specific subroutine for this generic subroutine call.   [PASTIXINITPARAM]
       CALL pastixInitParam( data%iparm_pastix, data%dparm_pastix )
------------^
../src/sls/sls.F90(1315): error #6285: There is no matching specific subroutine for this generic subroutine call.   [PASTIXINIT]
       CALL pastixInit( data%pastix_data, MPI_COMM_WORLD_pastix,               &
------------^
compilation aborted for ../src/sls/sls.F90 (code 1)
```

**Comment by amontoison** [comment]
I also tried to test the library `libpastix` with `pastixt.F90` but I have the following error:
```shell
FAILED: pastixt_double.p/src_external_pastix_pastixt.F90.o 
gfortran -Ipastixt_double.p -I. -I.. -I../include -Ilibpastix.so.p -Ilibspmf.so.p -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -g -DGALAHAD_DOUBLE -Jpastixt_double.p -o pastixt_double.p/src_external_pastix_pastixt.F90.o -c ../src/external/pastix/pastixt.F90
../src/external/pastix/pastixt.F90:9:7:

    9 |   USE spmf
      |       1
Fatal Error: Cannot open module file ‘spmf.mod’ for reading at (1): Aucun fichier ou dossier de ce type
```
With Meson, I don't have a `spmf.mod` or a `pastix.mod` when I compile them.
![Capture d’écran du 2023-01-09 14-01-11](https://user-images.githubusercontent.com/35051714/211314022-fd2dccb8-24a6-44e5-9410-2d4f231e4ee9.png)

**Comment by nimgould** [comment]
Works here for gfortran, nag, ifort and ifx. But what particularly are we talking about, I am simply using make -s -f $GALAHAD//makefiles/pc64.lnx.gfo all_standalone from $AGALAHD/src

For your other issue, partix iteslf doesn't provide the spmf and pastix modules, it seems to have been written by people who don't really have modern fortran at their hearts. I added these extra packages, the ones compiled in the pastix makemaster, i.e., $(PLGS)(spmf_enums.o) $(PLGS)(spmf_interfaces.o)  $(PLGS)(spmf.o) $(PLGS)(pastixf_enums.o)  $(PLGS)(pastixf_interfaces.o) $(PLGS)(pastixf.o)
, so that it does work with fortran 90. You need to compile these - spmf_enums.F90 spmf_interfaces.F90 spmf.F90 pastixf_enums.F90 pastixf_interfaces.F90 pastixf.F90 -  in this order, first, all are in $GALAHAD/src/dum. I should add that getting pastix to work was quite tricky!!

**Comment by amontoison** [comment]
I found the issue, we can't have single and double version of PasTiX in the same shared library (contrary to spmf).
I updated the Meson script to generate `libpastix_single` and `libpastrix_double`.

**Comment by nimgould** [comment]
Excellent. Well found

**Comment by amontoison** [comment]
> For your other issue, partix iteslf doesn't provide the spmf and pastix modules, it seems to have been written by people who don't really have modern fortran at their hearts. I added these extra packages, the ones compiled in the pastix makemaster, i.e., (PLGS)(spmfenums.o)(PLGS)(spmf_interfaces.o) (PLGS)(spmf.o)(PLGS)(pastixf_enums.o) (PLGS)(pastixfinterfaces.o)(PLGS)(pastixf.o) , so that it does work with fortran 90. You need to compile these - spmf_enums.F90 spmf_interfaces.F90 spmf.F90 pastixf_enums.F90 pastixf_interfaces.F90 pastixf.F90 - in this order, first, all are in $GALAHAD/src/dum. I should add that getting pastix to work was quite tricky!!

I compile the shared libraries and tests of `spmf` and `pastix` like that with Meson:
```
extra_args_single = ['-DGALAHAD_SINGLE']
extra_args_double = ['-DGALAHAD_DOUBLE']

libspmf_src = []
libpastix_src = []

libspmf_src += files('src/dum/spmf_enums.F90', 'src/dum/spmf_interfaces.F90', 'src/dum/spmf.F90', 'src/kinds/kinds.F90')

libspmf = library('spmf',
                  sources : libspmf_src,
                  link_with : [libgalahad_blas, libgalahad_lapack],
                  dependencies : blas_dep + lapack_dep,
                  install : true)

libpastix_src += files('src/dum/pastixf_enums.F90', 'src/dum/pastixf_interfaces.F90', 'src/dum/pastixf.F90', 'src/kinds/kinds.F90')

libpastix_single = library('pastix_single',
                    sources : libpastix_src,
                    link_with : [libgalahad_blas, libgalahad_lapack, libspmf],
                    dependencies : blas_dep + lapack_dep,
                    fortran_args : extra_args_single,
                    install : true)

libpastix_double = library('pastix_double',
                    sources : libpastix_src,
                    link_with : [libgalahad_blas, libgalahad_lapack, libspmf],
                    dependencies : blas_dep + lapack_dep,
                    fortran_args : extra_args_double,
                    install : true)

libgalahad_include = ['include']

pastixt_single = executable('pastixt_single', 'src/external/pastix/pastixt.F90', fortran_args : extra_args_single, link_with : [libspmf, libpastix_single], include_directories: libgalahad_include)
pastixt_double = executable('pastixt_double', 'src/external/pastix/pastixt.F90', fortran_args : extra_args_double, link_with : [libspmf, libpastix_double], include_directories: libgalahad_include)
test('pastix_single', pastixt_single, suite: ['fortran', 'single'], is_parallel : false)
test('pastix_double', pastixt_double, suite: ['fortran', 'double'], is_parallel : false)
```
Do you see something wrong Nick?

**Comment by nimgould** [comment]
No, this looks ok. Do I presume that it didn't work? If you are using the real pastix, I had to play with compiler flags to get things working. All of this external-solver stuff is documented in ./doc/README.external. Maybe this might help?

**Comment by nimgould** [comment]
Is this still an issue?

**Comment by amontoison** [comment]
Yes, is it possible to add a test specific to `spmf`? It will help me to isolate the problem.

**Comment by nimgould** [comment]
This is hard as this is not our software.

I will look again when I get home before our call

**Comment by amontoison** [comment]
fixed :heavy_check_mark:
