### ISSUE TITLE
Errors with the C interface of glrt

### ISSUE THREAD

**Issue by amontoison** [ralna/GALAHAD#44]
```shell
../src/glrt/C/glrt_ciface.F90:413:76:

  413 |   CALL f_glrt_solve_problem( fdata, status, n, power, weight, x, r, vector )
      |                                                                            1
Error: Type mismatch in argument ‘power’ at (1); passed REAL(8) to REAL(4)
[300/791] Compiling Fortran object libgalahad_double.so.p/src_sbls_sbls.F90.o
ninja: build stopped: subcommand failed.
```

**Comment by nimgould** [comment]
Can't see the problem at the moment, no objection here. I will investigate further this afternoon (I'm at the optician's this morning)

**Comment by nimgould** [comment]
I hadn't enabled single precision c interfaces in anything other than ugo (and even that was incorrect). I have pushed general changes. Does that help things?

**Comment by amontoison** [comment]
Yes, but I have the same error somewhere else now:
```shell
../src/lsrt/C/lsrt_ciface.F90:405:74:

  405 |   CALL f_lsrt_solve_problem( fdata, status, m, n, power, weight, x, u, v )
      |                                                                          1
Error: Type mismatch in argument ‘power’ at (1); passed REAL(8) to REAL(4)
```

If I only compile `libgalahad_c_double`, if have the following error:
```
../src/wcp/C/wcp_ciface.F90:449:7:

  449 |   USE GALAHAD_WCP_precision_ciface
      |       1
Fatal Error: Cannot open module file ‘galahad_wcp_double_ciface.mod’ for reading at (1): Aucun fichier ou dossier de ce type
compilation terminated.
```
We can't use `GALAHAD_WCP_double_ciface` because we are currently compiling it.

**Comment by nimgould** [comment]
The ../src/wcp/C/wcp_ciface.F90:449:7:
"error" should be ok as the the subroutine on starting on line 448 starts after the module has finished.

When I look at cltr_ciface, I see that the reals are defined with type rp_ while the integers are ipc_. I wonder if these reals should actually be rpc_ .... this is the case in ugo_ciface which works. No time to do this tonight, but will tomorrow.

**Comment by amontoison** [comment]
> The ../src/wcp/C/wcp_ciface.F90:449:7: "error" should be ok as the the subroutine on starting on line 448 starts after the module has finished.

Ok, the problem is somewhere else :thinking: 

> When I look at cltr_ciface, I see that the reals are defined with type rp_ while the integers are ipc_. I wonder if these reals should actually be rpc_ .... this is the case in ugo_ciface which works. No time to do this tonight, but will tomorrow.

:+1:

**Comment by nimgould** [comment]
I am not convinced this will help; I examined rp_ and rpc_ and both are 8 (4 for single) on the system here. I will make the changes, though.

I notice that optimization is disabled in your compilation (no -O* set) which presumably explains your rapid compile times. Also, you are using full checks (-Wall) which is good, but which is a time killer with optimization. I will disable optimization here and set -Wall temporarily, and recompile everything to see if I can reproduce your issues. I also notice you have -D_FILE_OFFSET_BITS=64, but don't imagine that this hurts anything.

Incidentally, the web page here has a column slider at the bottom of each box so that one can scan long lines. Any idea how to get one at the top, too? Currently I have to scroll down many pages to see what the first long line says...

**Comment by nimgould** [comment]
I was wrong, at least all of the warning messages vanished ... I wonder if that will fix the real(8) vs real(4) error?? Updates pushed

**Comment by amontoison** [comment]
Nick, you just need highlight the line that you want to see, you don't need the column slider.
I did a short video to show you:
https://user-images.githubusercontent.com/35051714/211801215-657db064-d65b-4aee-8a1c-d5c4af4a47d2.mp4

**Comment by amontoison** [comment]
> I was wrong, at least all of the warning messages vanished ... I wonder if that will fix the real(8) vs real(4) error?? Updates pushed

I will test it now.

**Comment by amontoison** [comment]
I still have an error but it's not the same file!
```
Error: Type mismatch in argument ‘radius’ at (1); passed REAL(8) to REAL(4)
[514/1167] Compiling Fortran object libgalahad_c_single.so.p/src_roots_C_roots_ciface.F90.o
../src/roots/C/roots_ciface.F90:79:19:

   79 |     fcontrol%tol = ccontrol%tol
      |                   1
```

**Comment by amontoison** [comment]
I pushed the last commits, you can switch to my branch to reproduce the error:
```
git checkout meson-build
meson setup builddir -Dciface=true
meson compile -C builddir
meson test -C builddir
```

**Comment by amontoison** [comment]
With Intel compiler I have the following messages:
```shell
ifort -Ilibgalahad_c_single.dylib.p -I. -I.. -I../include -Ilibspral_ssids_single.dylib.p -Ilibgalahad_hsl_single.dylib.p -Ilibgalahad_single.dylib.p -warn general -warn truncated_source -g -traceback -O0 -g -DGALAHAD_SINGLE -module libgalahad_c_single.dylib.p -gen-dep=libgalahad_c_single.dylib.p/src_gltr_C_gltr_ciface.F90.o -gen-depformat=make -o libgalahad_c_single.dylib.p/src_gltr_C_gltr_ciface.F90.o -c ../src/gltr/C/gltr_ciface.F90
../src/gltr/C/gltr_ciface.F90(425): error #6633: The type of the actual argument differs from the type of the dummy argument.   [RADIUS]
  CALL f_gltr_solve_problem( fdata, status, n, radius, x, r, vector )
-----------------------------------------------^
../src/gltr/C/gltr_ciface.F90(425): error #6633: The type of the actual argument differs from the type of the dummy argument.   [X]
  CALL f_gltr_solve_problem( fdata, status, n, radius, x, r, vector )
-------------------------------------------------------^
../src/gltr/C/gltr_ciface.F90(425): error #6633: The type of the actual argument differs from the type of the dummy argument.   [R]
  CALL f_gltr_solve_problem( fdata, status, n, radius, x, r, vector )
----------------------------------------------------------^
../src/gltr/C/gltr_ciface.F90(425): error #6633: The type of the actual argument differs from the type of the dummy argument.   [VECTOR]
  CALL f_gltr_solve_problem( fdata, status, n, radius, x, r, vector )
-------------------------------------------------------------^
compilation aborted for ../src/gltr/C/gltr_ciface.F90 (code 1)
```
```shell
FAILED: libgalahad_c_single.dylib.p/src_glrt_C_glrt_ciface.F90.o libgalahad_c_single.dylib.p/galahad_glrt_precision_ciface.mod 
ifort -Ilibgalahad_c_single.dylib.p -I. -I.. -I../include -Ilibspral_ssids_single.dylib.p -Ilibgalahad_hsl_single.dylib.p -Ilibgalahad_single.dylib.p -warn general -warn truncated_source -g -traceback -O0 -g -DGALAHAD_SINGLE -module libgalahad_c_single.dylib.p -gen-dep=libgalahad_c_single.dylib.p/src_glrt_C_glrt_ciface.F90.o -gen-depformat=make -o libgalahad_c_single.dylib.p/src_glrt_C_glrt_ciface.F90.o -c ../src/glrt/C/glrt_ciface.F90
../src/glrt/C/glrt_ciface.F90(413): error #6633: The type of the actual argument differs from the type of the dummy argument.   [POWER]
  CALL f_glrt_solve_problem( fdata, status, n, power, weight, x, r, vector )
-----------------------------------------------^
../src/glrt/C/glrt_ciface.F90(413): error #6633: The type of the actual argument differs from the type of the dummy argument.   [WEIGHT]
  CALL f_glrt_solve_problem( fdata, status, n, power, weight, x, r, vector )
------------------------------------------------------^
../src/glrt/C/glrt_ciface.F90(413): error #6633: The type of the actual argument differs from the type of the dummy argument.   [X]
  CALL f_glrt_solve_problem( fdata, status, n, power, weight, x, r, vector )
--------------------------------------------------------------^
../src/glrt/C/glrt_ciface.F90(413): error #6633: The type of the actual argument differs from the type of the dummy argument.   [R]
  CALL f_glrt_solve_problem( fdata, status, n, power, weight, x, r, vector )
-----------------------------------------------------------------^
../src/glrt/C/glrt_ciface.F90(413): error #6633: The type of the actual argument differs from the type of the dummy argument.   [VECTOR]
  CALL f_glrt_solve_problem( fdata, status, n, power, weight, x, r, vector )
--------------------------------------------------------------------^
compilation aborted for ../src/glrt/C/glrt_ciface.F90 (code 1)
```

**Comment by nimgould** [comment]
The line 
FAILED: libgalahad_c_single.dylib.p/src_glrt_C_glrt_ciface.F90.o libgalahad_c_single.dylib.p/galahad_glrt_precision_ciface.mod 
is very suspicious ... in particular, the galahad_glrt_precision_ciface.mod part.
I don't know how this line is generated, but I would have expected galahad_glrt_single_ciface.mod. 

As I said, the standard makefile route does not have this issue

**Comment by nimgould** [comment]
This failed message comes from the previous
[617/1167] Compiling Fortran object li...p/src_presolve_C_presolve_ciface.F90.o
where I don't know what the ... is hiding

**Comment by amontoison** [comment]
Nick, I probably found the culprit.
It seems that you deleted the folder `precision` after my visit at RAL.
I don't have any error when I compile packages with C interfaces like `UGO` on the `meson-mp` branch.
https://github.com/ralna/GALAHAD/blob/meson-mp/meson.build

**Comment by nimgould** [comment]
Sorry (even if I don't really understand ... where is the precision folder? Where should it be created?)

**Comment by amontoison** [comment]
It is this folder: https://github.com/ralna/GALAHAD/tree/meson-mp/src/precision

**Comment by nimgould** [comment]
OK, I forgot what this folder is for. Should I add it to the git distro? The meson-mp version seems to have a very old file precision.F90 file that is now in the kind folder (as kind.F90). Maybe that is the issue?

**Comment by amontoison** [comment]
> OK, I forgot what this folder is for. Should I add it to the git distro? The meson-mp version seems to have a very old file precision.F90 file that is now in the kind folder (as kind.F90). Maybe that is the issue?

Ok, good to know because we need to compile it before the other packages such as `common`.
I added `kinds.F90` in the source files for the C library and it seem to solve the issue.
I have this error but it related to something else:
```
[429/1572] Compiling Fortran object libgalahad_c_single.so.p/src_qpa_C_qpa_ciface.F90.o
FAILED: libgalahad_c_single.so.p/src_qpa_C_qpa_ciface.F90.o libgalahad_c_single.so.p/galahad_qpa_precision_ciface.mod 
gfortran -Ilibgalahad_c_single.so.p -I. -I.. -I../include -Ilibspral_ssids_single.so.p -Ilibgalahad_hsl_single.so.p -Ilibgalahad_single.so.p -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -g -fPIC -DGALAHAD_SINGLE -DSPRAL_SINGLE -Jlibgalahad_c_single.so.p -o libgalahad_c_single.so.p/src_qpa_C_qpa_ciface.F90.o -c ../src/qpa/C/qpa_ciface.F90
../src/qpa/C/qpa_ciface.F90:124:30:

  124 |       INTEGER ( KIND = ip_ ) ( KIND = C_INT64_T ) :: factorization_integer
      |                              1
Error: Syntax error in data declaration at (1)
../src/qpa/C/qpa_ciface.F90:125:30:

  125 |       INTEGER ( KIND = ip_ ) ( KIND = C_INT64_T ) :: factorization_real
      |                              1
Error: Syntax error in data declaration at (1)
../src/qpa/C/qpa_ciface.F90:375:65:

  375 |     finform%factorization_integer = cinform%factorization_integer
      |                                                                 1
Error: ‘factorization_integer’ at (1) is not a member of the ‘qpa_inform_type’ structure; did you mean ‘factorization_status’?
../src/qpa/C/qpa_ciface.F90:376:59:

  376 |     finform%factorization_real = cinform%factorization_real
      |                                                           1
Error: ‘factorization_real’ at (1) is not a member of the ‘qpa_inform_type’ structure; did you mean ‘factorization_status’?
../src/qpa/C/qpa_ciface.F90:415:34:

  415 |     cinform%factorization_integer = finform%factorization_integer
      |                                  1
Error: ‘factorization_integer’ at (1) is not a member of the ‘qpa_inform_type’ structure; did you mean ‘factorization_status’?
../src/qpa/C/qpa_ciface.F90:416:31:

  416 |     cinform%factorization_real = finform%factorization_real
      |                               1
Error: ‘factorization_real’ at (1) is not a member of the ‘qpa_inform_type’ structure; did you mean ‘factorization_status’?
```

**Comment by nimgould** [comment]
With luck, I squashed those bugs

**Comment by amontoison** [comment]
Yes, I'm able to compile all C interfaces now! I will be able to test C examples and tests.
Can I test C examples in single and double precision or only double precision like Fortran ones?

**Comment by nimgould** [comment]
Both the fortran and C tests (those files ending in t.F90, ti.F90 and t#.F90 for natural numbers #) can be tested in both single and double (but of course, the tests are less likely to succeed in single for precision reasons). The same for the C examples, there is pre-processing option to provide the required (real) precision via compiler flags
