### ISSUE TITLE
Build HSL-free version

### ISSUE THREAD

**Issue by dpo** [ralna/GALAHAD#6]
@nimgould I tried to build a standalone version of GALAHAD without CUTEst, Matlab, Python, and HSL, but quickly got errors related to building certain HSL modules, such as
```
make[3]: *** No rule to make target `/ma27/ma27d.f', needed by `/Users/dpo/dev/ralna/GALAHAD/objects/mac64.osx.gfo/double/libgalahad_hsl.a(ma27d.o)'.  Stop.
```

**Comment by nimgould** [comment]
I believe that this is now fixed
