### ISSUE TITLE
ugot2 test takes more than 30 seconds

### ISSUE THREAD

**Issue by amontoison** [ralna/GALAHAD#73]
```
 58/226 GALAHAD:ugo+fortran+single / ugot2_single                                 TIMEOUT        30.01s   killed by signal 15 SIGTERM
>>> MALLOC_PERTURB_=70 /home/alexis/Bureau/git/GALAHAD/builddir/ugot2_single

171/226 GALAHAD:ugo+fortran+double / ugot2_double                                 TIMEOUT        30.01s   killed by signal 15 SIGTERM
>>> MALLOC_PERTURB_=25 /home/alexis/Bureau/git/GALAHAD/builddir/ugot2_double
```

**Comment by nimgould** [comment]
This test needs user interaction (pick a number between 1 and 23. I suggest you miss this out from your tests

**Comment by amontoison** [comment]
Is it possible to modify the test such that we can also provide the number as an argument?
```
./ugot2_single 5
```

**Comment by nimgould** [comment]
We could, but this test is identical to ugot except that  this loops over all 23 examples while this one
addresses a single user-specified one.

**Comment by amontoison** [comment]
In that case, maybe we should just rename it as an example and not a test?

**Comment by nimgould** [comment]
I can do that ... later

**Comment by amontoison** [comment]
Let's just compile it for now and not use it as a Meson test.
I didn't that it needed a user interaction.

**Comment by nimgould** [comment]
Renamed as ugos3.f90

**Comment by amontoison** [comment]
Perfect Nick!
For the Fortran packages, `PasTiX`, `SPRAL`and `SSIDS` are the last ones.
All the other Fortran packages with their examples and tests are compiled in single / double precision with Meson.

**Comment by nimgould** [comment]
Could you try the pastix test again, it works here now

**Comment by amontoison** [comment]
It solved the problem, thanks Nick!
