### ISSUE TITLE
Unit tests should not test CUTEst interface if CUTEst is not part of the build

### ISSUE THREAD

**Issue by dpo** [ralna/GALAHAD#8]
@nimgould After building with the changes described in #7, I ran
```
make -f /Users/dpo/dev/ralna/GALAHAD/makefiles/mac64.osx.gfo tests
```
as indicated in the `README`, but got the error
```
echo " Testing SIF interface to LANCELOT B"
 Testing SIF interface to LANCELOT B
cd /Users/dpo/dev/ralna/GALAHAD/examples ; sdgal mac64.osx.gfo lancelot ALLINITC
/bin/sh: sdgal: command not found
make[1]: *** [test_cutest_double] Error 127
make: *** [tests_double] Error 2
``` 
It seems the unit tests try to test the CUTEst interface even though I built a standalone CUTEst-free version.

**Comment by nimgould** [comment]
Now fixed. Default test
  make -s -f (architecture) test
now only performs comprehensive tests. To test with additional CUTEst/SIF interfaces, use
 make -s -f (architecture) tests
