### ISSUE TITLE
Continuous integration for Silicon Mac

### ISSUE THREAD

**Issue by dpo** [ralna/GALAHAD#80]
CirrusCI provides Silicon VMs. We should test
- [x] gcc/gfortran
- [ ] icc/ifort

**Comment by jfowkes** [comment]
@dpo github actions now provide silicon VMs:
https://github.blog/changelog/2022-08-09-github-actions-self-hosted-runners-now-support-apple-m1-hardware/

**Comment by dpo** [comment]
@jfowkes That page is for self-hosted runners. I've been using those for a while. But GitHub-hosted runners don't support Silicon yet: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

**Comment by jfowkes** [comment]
@dpo sorry yes you're correct, let's hope they add support soon!

**Comment by amontoison** [comment]
I use CirrusCI for testing my Julia code on FreeBSD and Apple M1 platforms.
