### ISSUE TITLE
Error with Intel compilers

### ISSUE THREAD

**Issue by amontoison** [ralna/GALAHAD#82]
I have this error Nick after your modifications of the `kinds` module.
```
FAILED: libgalahad_hsl_double.so.p/src_zd11_zd11.F90.o libgalahad_hsl_double.so.p/hsl_zd11_precision.mod 
ifort -Ilibgalahad_hsl_double.so.p -I. -I.. -I../include -Ilibgalahad_lapack.so.p -Ilibgalahad_blas.so.p -D_FILE_OFFSET_BITS=64 -warn general -warn truncated_source -g -traceback -O0 -g -fPIC -DGALAHAD_DOUBLE -DSPRAL_DOUBLE -DSPRAL_NO_HWLOC -DSPRAL_HAVE_SCHED_GETCPU -module libgalahad_hsl_double.so.p -gen-dep=libgalahad_hsl_double.so.p/src_zd11_zd11.F90.o -gen-depformat=make -o libgalahad_hsl_double.so.p/src_zd11_zd11.F90.o -c ../src/zd11/zd11.F90
../src/zd11/zd11.F90(12): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [GALAHAD_KINDS_DOUBLE]
     USE GALAHAD_KINDS_double
---------^
../src/zd11/zd11.F90(19): error #6683: A kind type parameter must be a compile-time constant.   [IP_]
       INTEGER ( KIND = ip_ ) :: m, n, ne
------------------------^
../src/zd11/zd11.F90(21): error #6683: A kind type parameter must be a compile-time constant.   [IP_]
       INTEGER ( KIND = ip_ ), ALLOCATABLE, DIMENSION( : ) :: row, col, ptr
------------------------^
../src/zd11/zd11.F90(22): error #6683: A kind type parameter must be a compile-time constant.   [RP_]
       REAL ( KIND = rp_ ), ALLOCATABLE, DIMENSION( : ) :: val
---------------------^
../src/zd11/zd11.F90(30): error #6683: A kind type parameter must be a compile-time constant.   [IP_]
     INTEGER ( KIND = ip_ ), INTENT( OUT ) ::  stat
----------------------^
../src/zd11/zd11.F90(34): error #6683: A kind type parameter must be a compile-time constant.   [IP_]
     INTEGER ( KIND = ip_ ) :: i, l
----------------------^
../src/zd11/zd11.F90(53): error #6683: A kind type parameter must be a compile-time constant.   [IP_]
     INTEGER ( KIND = ip_ ) :: i
----------------------^
compilation aborted for ../src/zd11/zd11.F90 (code 1)
```

**Comment by nimgould** [comment]
I suggests that it can't find GALAHAD_KINDS_double. That is one of the three modules
contained in the file kinds.F90. Has this not compiled correctly?

**Comment by nimgould** [comment]
Let me know if this persists. When you compile kinds.F90, it should generate three mod files

galahad_kinds_double.mod  
galahad_kinds_single.mod
galahad_kinds.mod

**Comment by amontoison** [comment]
I rebased the branch `meson-build` and I don't have this error anymore.

I have another issue related to `build_spec` with Intel compilers.
```
[503/2062] Linking target buildspec_single
FAILED: buildspec_single 
c++  -o buildspec_single buildspec_single.p/src_buildspec_buildspec.F90.o -Wl,--as-needed -Wl,--no-undefined '-Wl,-rpath,$ORIGIN/' -Wl,-rpath-link,/home/runner/work/GALAHAD/GALAHAD/builddir/ -Wl,--start-group libgalahad_single.so -lifcore -limf -Wl,--end-group
/usr/bin/ld: buildspec_single.p/src_buildspec_buildspec.F90.o: relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
```
Can you test the Meson build system with Intel compilers on your computer Nick?

**Comment by nimgould** [comment]
Will do ... once I find the instructions to do this again I have them somewhere)

**Comment by nimgould** [comment]
Hmmm, I must have an old version, it only compiles ugo and its tests. Please remind me what I need to do to use meson, presumably I need to be on another branch

**Comment by nimgould** [comment]
ok, I think all I need to do is rebase to meson-build. 

When I used the instructions in README.meson to set CC=icc FC=ifort meson setup builddir,
the resulting meson compile -C builddir still uses gcc/gfortran. This compile fails saying that it cannot find galahad_kinds_single.mod, while should have been compiled from kinds.F90. But I cannot find a list of which compiles have happened,  and there is no kinds*.p Has the order of compilation not worked?

Also how do I actually use ifort (etc)?

**Comment by amontoison** [comment]
You probably have an old installation of our Meson script. Just remove the `builddir` folder.
It should work with the following command:
```
git fetch origin
git checkout meson-build
rm -rf builddir
CC=icc FC=ifort meson setup builddir -Dciface=true
meson compile -C builddir
meson test -C builddir
```
You can recover your working branch after with
```
git checkout multi-precision
```

**Comment by nimgould** [comment]
Its a horrible mess! 

Once I did a git checkout meson-build, I got 

Switched to branch 'meson-build'
Your branch and 'origin/meson-build' have diverged,
and have 33 and 101 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

so I tried git pull, which failed with

auto-merging .github/workflows/standalone.yml
CONFLICT (add/add): Merge conflict in .github/workflows/standalone.yml
Auto-merging meson.build
CONFLICT (add/add): Merge conflict in meson.build
Auto-merging meson_options.txt
CONFLICT (add/add): Merge conflict in meson_options.txt
Auto-merging src/dum/meson.build
CONFLICT (add/add): Merge conflict in src/dum/meson.build
Auto-merging src/kinds/meson.build
CONFLICT (add/add): Merge conflict in src/kinds/meson.build
Automatic merge failed; fix conflicts and then commit the result.

I then removed these files, and tried another git pull, which then
says

error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.

git status says that there are hundreds of files that need committing, but these are all ones that I committed over the last few weeks, i.e., almost everything in ./src. So I tried another

 git checkout meson-build

.github/workflows/standalone.yml: needs merge
meson.build: needs merge
meson_options.txt: needs merge
src/dum/meson.build: needs merge
src/kinds/meson.build: needs merge

but this grumbles about 

.github/workflows/standalone.yml: needs merge
meson.build: needs merge
meson_options.txt: needs merge
src/dum/meson.build: needs merge
src/kinds/meson.build: needs merge

the very files I deleted because of previous conflicts. 

Thus I am once again in an ocean of git pain, and I don't know
which files are current and which aren't ... I certainly don't want
to loose anything I already committed in multi-precision! 

I can't even get back to multi-precision as this says the same thing about 
needing to merge .github/workflows/standalone.yml (etc).

**Comment by amontoison** [comment]
Ok Nick don't worry, `git` gave you a wrong advise with `git pull`.
The good solution was `git rebase origin/meson-build`.

To solve your problem, you just need to abort your current merge with `git merge --abort`.
You should be able to do `git rebase origin/meson-build` just after.

For information `git pull` is equivalent to `git fetch` + `git merge`.
In general it's what we use when we don't modify the history of the commits.
It's perfect for your branch `multi-precision` because you just add new commits on this branch, no fancy things.

For the branch `meson-build` I modify the commit history quite often because I rebase the branch with your branch `multi-precision` to always include your last modifications.
It means that the commits related to Meson are always on top of those of the branch `multi-precision`.
`git fetch` + `git rebase origin/meson-build` is needed for this branch, otherwise git doesn't understand why the local and remote branch have diverged,

**Comment by nimgould** [comment]
Thank you ... that saved my day!

I now see that I need to make a change (to src/dum/mpi.F90).
Do I rebase to my branch, change, commit and push, and then
rebase back to meson-build? Will the change be automatically
included in meson-build, or do I change on both branches?

**Comment by amontoison** [comment]
Now you just need to checkout your branch `multi-precision` with:
```
git checkout multi-precision
```
, make a change, commit and push (as before).
When it's done, you can come back to `meson-build` with
```
git checkout meson-build
```
and rebase back to meson-build
```
git rebase multi-precision (local branch multi-precision)
```
or
```
git fetch origin
git rebase origin/multi-precision (remote branch multi-precision)
```
After that the change related to `src/dum/mpi.F90` will be on both branches.

**Comment by nimgould** [comment]
Thank you. All is now fine. Returning to the compile, I get three errors up to [223/2062].

The first two are effectively the same, the c++ compiler needs libifcore.so and libimf.so. Both are provided as part of the intel oneapi distro in 
/opt/ntel/compilers_and_libraries_2020.1.217/linux/compiler/lib/intel64/ (or ia32/ )
but I  don't know how to point meson to find them.

The third is that compiling src/dum/mpi.F90 says that it cannot open the compiled module file
(which it doesn't say but I deduce that it is for GALAHAD_KINDS_double and thus cannot find the definitions of ip_ (which is defined in this module). I have no idea why this happens, it works in the makefile version.

**Comment by nimgould** [comment]
I was also expecting to see a libspral.so somewhere, is that not generated? In the makefile version, the spral parts are kept separate from the galahad parts

**Comment by amontoison** [comment]
> I was also expecting to see a libspral.so somewhere, is that not generated? In the makefile version, the spral parts are kept separate from the galahad parts

No, it's not generated as a standalone library.
I plan to fix it and it's why I asked you in my previous mail to send me an archive with the generated libraries by your makefile version such that I check what is different.
I will update the meson script.

**Comment by nimgould** [comment]
Sorry, I forgot

libgalahad.a
libgalahad_blas.a
libgalahad_c.a
libgalahad_cutest.a
libgalahad_cutest_dummy.a
libgalahad_dummy.a
libgalahad_hsl.a
libgalahad_hsl_c.a
libgalahad_lapack.a
libgalahad_metis4.a
libgalahad_mkl_pardiso.a
libgalahad_mpi.a
libgalahad_mumps.a
libgalahad_pardiso.a
libgalahad_pastix.a
libgalahad_spral.a
libgalahad_umfpack.a
libgalahad_wsmp.a

**Comment by amontoison** [comment]
> Woops, I also need set CXX=icpc along with the FC and CC. Then the missing -lifcore -limf messages disappear.

Thanks for the tip!! I updated the continuous integration script to use it.
 
> Now I get
> 
> [312/2062] Compiling Fortran object li...ngle.so.p/src_spral_core_analyse.F90.o FAILED: libgalahad_single.so.p/src_spral_core_analyse.F90.o libgalahad_single.so.p/spral_core_analyse_precision.mod ifort -Ilibgalahad_single.so.p -I. -I.. -I../include -Ilibgalahad_cpp_single.so.p -Ilibgalahad_metis.so.p -Ilibpastix_single.so.p -Ilibwsmp.so.p -Ilibspmf_single.so.p -Ilibmumps_single.so.p -Ilibmkl_pardiso.so.p -Ilibpardiso.so.p -Ilibgalahad_hsl_single.so.p -Ilibgalahad_lapack.so.p -Ilibgalahad_blas.so.p -D_FILE_OFFSET_BITS=64 -warn general -warn truncated_source -g -traceback -O0 -g -fPIC -DGALAHAD_SINGLE -DSPRAL_SINGLE -DSPRAL_NO_HWLOC -DSPRAL_HAVE_SCHED_GETCPU -module libgalahad_single.so.p -gen-dep=libgalahad_single.so.p/src_spral_core_analyse.F90.o -gen-depformat=make -o libgalahad_single.so.p/src_spral_core_analyse.F90.o -c ../src/spral/core_analyse.F90
> 
> Where do I find what the missing part of the statement
> 
> Compiling Fortran object li...ngle.so.p/src_spral_core_analyse.F90
> is? What is the ... presumably this is written to a log file somewhere?

The line with `...` is not displayed because the error doesn't come from this line.
The failure is below the `[FAILED]` block and it's for that reason that we can see the full compilation command.

> The next line
> 
> FAILED: libgalahad_single.so.p/src_spral_core_analyse.F90.o libgalahad_single.so.p/spral_core_analyse_precision.mod
> 
> looks odd, should the word precision have been translated into single?

Yes, `precision` has been translated into single, I checked last time to be sure that another error was not related to it.
 
> It then looks as if it can't find the spral_kinds_single.mod file, but there is one generated in ./builddir/libgalahad_single.so.p/ and if I understand the command ifort -Ilibgalahad_single.so.p -I. -I.. -I../include -Ilibgalahad_cpp_single.so.p -Ilibgalahad_metis.so.p -Ilibpastix_single.so.p -Ilibwsmp.so.p -Ilibspmf_single.so.p -Ilibmumps_single.so.p -Ilibmkl_pardiso.so.p -Ilibpardiso.so.p -Ilibgalahad_hsl_single.so.p -Ilibgalahad_lapack.so.p -Ilibgalahad_blas.so.p -D_FILE_OFFSET_BITS=64 -warn general -warn truncated_source -g -traceback -O0 -g -fPIC -DGALAHAD_SINGLE -DSPRAL_SINGLE -DSPRAL_NO_HWLOC -DSPRAL_HAVE_SCHED_GETCPU -module libgalahad_single.so.p -gen-dep=libgalahad_single.so.p/src_spral_core_analyse.F90.o -gen-depformat=make -o libgalahad_single.so.p/src_spral_core_analyse.F90.o -c ../src/spral/core_analyse.F90
> 
> that directory is on the path.
> 
> I'm sorry but I am having trouble understanding what meson is trying to do here

I will generate a standalone `libspral.so` library.

**Comment by amontoison** [comment]
> 

Did you merge single and double precision for all libraries or you just add `_single` and `_double` at the end the names?

**Comment by nimgould** [comment]
In case it helps ... 

ar t libgalahad_spral.a
dummy_spral.o
kinds.o
matrix_util.o
random.o
rutherford_boeing.o
cuda_nocuda.o
compat.o
guess_topology.o
omp.o
NumericSubtree.o
profile.o
SymbolicSubtree.o
cholesky.o
ldlt_app.o
ldlt_nopiv.o
ldlt_tpp.o
wrappers.o
ThreadStats.o
hw_topology.o
metis4_wrapper.o
scaling.o
match_order.o
datatypes.o
core_analyse.o
pgm.o
inform.o
contrib.o
subtree.o
akeep.o
blas_iface.o
lapack_iface.o
cpu_iface.o
cpu_subtree.o
profile_iface.o
gpu_subtree_no_cuda.o
fkeep.o
contrib_free.o
anal.o
ssids.o

The _single/_double.o will be added at compile time in the combined version

**Comment by amontoison** [comment]
Ok, perfect. I will update the name of libraries tonight.
Have you thought about a `libgalahad_common.so` library that contains the `kinds` package?
It will be easier to link all libraries with various precision with it directly.

**Comment by amontoison** [comment]
> In case it helps ...
> 
> ar t libgalahad_spral.a dummy_spral.o kinds.o matrix_util.o random.o rutherford_boeing.o cuda_nocuda.o compat.o guess_topology.o omp.o NumericSubtree.o profile.o SymbolicSubtree.o cholesky.o ldlt_app.o ldlt_nopiv.o ldlt_tpp.o wrappers.o ThreadStats.o hw_topology.o metis4_wrapper.o scaling.o match_order.o datatypes.o core_analyse.o pgm.o inform.o contrib.o subtree.o akeep.o blas_iface.o lapack_iface.o cpu_iface.o cpu_subtree.o profile_iface.o gpu_subtree_no_cuda.o fkeep.o contrib_free.o anal.o ssids.o
> 
> The _single/_double.o will be added at compile time in the combined version

Thanks Nick!
I forgot to open an issue about it but I encountered an error if I replace `metis4_wrapper.F90` by `metis5_wrapper.F90`.

**Comment by amontoison** [comment]
Oh you're right, I forgot the project with the mixed library.

**Comment by amontoison** [comment]
I also have a `libwsmp` and `libspmf` but not a `libgalahad_umfpack`.
What is the result of `ar t libXXX.so` for the following libraries please?
```
libgalahad_cutest.a
libgalahad_cutest_dummy.a
libgalahad_dummy.a
libgalahad_mpi.a
libgalahad_umfpack.a
```

**Comment by nimgould** [comment]
ar t libgalahad_cutest.a 
empty
uselancelot.o
cutest_functions.o
useeqp.o
useqpa.o
useqpb.o
useqpc.o
useblls.o
usebqp.o
usebqpb.o
usecqp.o
usedqp.o
usecdqp.o
useqp.o
usedlp.o
uselpa.o
uselpb.o
usells.o
usel1qp.o
usepresolve.o
usetrs.o
userqs.o
usedps.o
usegltr.o
useglrt.o
uselstr.o
uselsrt.o
usel2rt.o
usefiltrane.o
usewcp.o
usefdh.o
usetru.o
usearc.o
usetrb.o
usenls.o
useugo.o
usebgo.o
usedgo.o

ar t libgalahad_cutest_dummy.a 
cutest_dummy.o

ar t libgalahad_dummy.a 
dummy.o

ar t libgalahad_mpi.a 
mpi.o

&

ar t libgalahad_umfpack.a
umfpack.o

You won't need the cutest ones for julia, and libgalahad_dummy.a is just used as do-nothing substitute for some builds (not needed here, I suspect). The file "empty" is a blank file so that linking with libgalahad_cutest.a has something if proper cutest isn't required.

**Comment by nimgould** [comment]
Merging the single/double is more complicated than I thought; trying to disentangle the C++ in spral needs more thought if we mix the two precisions. I'm sure it's possible, its just a horrible mess!

**Comment by amontoison** [comment]
Let's merge the other GALAHAD packages together first and link them with `-lspral_single -lspral_double`.
